### ISSUE TITLE
README: some comments

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-rust#20]
> Starlark has at least 3 implementations: a Java one for Bazel, a go one and this one.

"Go", not "go".

> This interpreter was made using the specification from the go version and the Python 3 documentation when things were unclear.

What was unclear? Please file a bug report against doc/spec.md for each issue and I will fix them by clarifying the spec.

> It does not include the set() type either (the Java implementation use a custom type, depset, instead).

The depset data type is a feature of the Bazel build language, not core Starlark. (I have a Go implementation but it does not belong in the Starlark-in-Go repository.)

**Comment by damienmg** [comment]
> > Starlark has at least 3 implementations: a Java one for Bazel, a go one and this one.
> 
> "Go", not "go".

:) Fixed

> 
> > This interpreter was made using the specification from the go version and the Python 3 documentation when things were unclear.
> 
> What was unclear? Please file a bug report against doc/spec.md for each issue and I will fix them by clarifying the spec.
> 

I don't remember everything because I did most of the work in February, but the main issue was an unclear grammar. I had to refer to the python 3 specification to make the grammar non ambiguous. I wanted to upload the result of the grammar in the skylark spec but haven't found the time to format it so far.

> > It does not include the set() type either (the Java implementation use a custom type, depset, instead).
> 
> The depset data type is a feature of the Bazel build language, not core Starlark. (I have a Go implementation but it does not belong in the Starlark-in-Go repository.)

The spec on the go repository talks about [sets](https://github.com/google/skylark/blob/master/doc/spec.md#sets). I modified the readme to replace the text about Java by the fact that the starlark spec does not have set.

**Comment by damienmg** [comment]
I consider this one as solved since it was addressed the best I could.
