### ISSUE TITLE
FileLoader should ideally use Path/PathBuf's instead of `&str`

### ISSUE THREAD

**Issue by Mythra** [google/starlark-rust#274]
It seems the `FileLoader` implementation accepts a path as a `&str`. While this is simplistic allowing for someone to simply time `load("my_constant_file")`, this actually presents a theoretical problem as Linux Path's aren't guaranteed to be UTF8, but rust string types are. Rust offers both [Path](https://doc.rust-lang.org/std/path/struct.Path.html), and [PathBuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html) for dealing with paths (which do work for non-utf8 paths, and they also handle path separators for you).

**Comment by illicitonion** [comment]
This sounds very reasonable! Can I tempt you to put together a pull request?

Ideally it would take an `AsRef<Path>` for maximum flexibility, and so that the existing code passing `&str` would continue to work, but as it's a function on a trait I think we'd have to settle for `&Path` (which feels like a reasonable type to use).

**Comment by Mythra** [comment]
I could be tempted yes! I more just filed to ensure this was reasonable. Since Path is non owning anyway I think we can just accept `Path`, but I'll definitely play around with it. Thanks for the quick response!

**Comment by Mythra** [comment]
As show in #276 , since load in starlark accepts only utf-8 strings, there's really not much point in supporting the `Path` type, as it'd basically be impossible to load anyway.
