### ISSUE TITLE
add string·elem_ords

### ISSUE THREAD

**Issue by josharian** [google/starlark-rust#67]
spec: https://github.com/google/starlark-go/blob/master/doc/spec.md#string·elem_ords

```
$ starlark-go -c "''.elem_ords()"

(exit 0)

$ starlark-rust -c "''.elem_ords()"
error[CV00]: Cannot .elem_ords on type string
 --> [command flag]:1:1
  |
1 | ''.elem_ords()
  | ^^^^^^^^^^^^ .elem_ords not supported for type string

(exit 2)
```

**Comment by illicitonion** [comment]
As far as I can tell, starlark-rust's current implementation of `elems` does what the spec says `elem_ords` should do.

`elems` itself is interestingly specified... Rust doesn't really have a native concept of a byte string absent a charset in the way that Go does, so there isn't a particularly natural implementation for `elems`...

**Comment by josharian** [comment]
Probably the spec should say something about this, but I’m guessing the answer is UTF-8. cc @alandonovan

**Comment by adonovan** [comment]
There is consensus that it is infeasible to specify the string encoding in a way that does not impose an intolerable performance penalty on at least one implementation, so each impl is free to define the element type of string as it wishes. Starlark-Java's strings are sequences of UTF-16 codes, Starlark-Go's strings are sequences of UTF-16 codes, and judging from the test suite, Starlark-Rust's strings are sequences of Unicode code points. (A poor choice from a performance perspective, but a legal one.)  All of the string operations are defined in terms of elements, not bytes/chars/codepoints.  The elem_ords method for Starlark-Rust should return a sequence of code points as integers.

**Comment by illicitonion** [comment]
> The elem_ords method for Starlark-Rust should return a sequence of code points as integers.

Yeah, `elem_ords` is easy - bytes can be represented as numbers in an obvious way; the question here is about `elems` - it appears to return a string representation of arbitrary single bytes. In the Go implementation, these end up as strings like `\xe4`, but because rust treats strings much more as utf-8 and much less like bytes, there isn't an obvious string-ified version of a byte. We could use an escaped string `\\xe4`, but that is more of a debug representation - if you were to join it with some other bytes, there would be slashes, rather than code-points merging into multi-byte characters.

**Comment by andrewchambers** [comment]
I think a third option would be to lazily compute and cache the char array per string only if it is requested. I don't know how common it is for your use case, but for mine, string manipulation from the starlark side is pretty rare.
